<?xml version="1.0" encoding="UTF-8"?>
<settings>
  <developer_mode>${settings.developer_mode!}</developer_mode>                           
  <projection>${settings.projection!'mercator'}</projection>                           
  <width>${settings.width!}</width>                                             
  <height>${settings.height!}</height>                                           
  <font>${settings.font!'Tahoma'}</font>                                         
  <text_size>${settings.text_size!'11'}</text_size>                                   
  <text_color>${settings.text_color!}</text_color>                                   
  <decimals_separator>${settings.decimals_separator!'.'}</decimals_separator>                   
  <thousands_separator>${settings.thousands_separator!','}</thousands_separator>                 
  <redraw>${settings.redraw!}</redraw>                                           
  <precision>${settings.precision!}</precision>                                     
  <reload_data_interval>${settings.reload_data_interval!}</reload_data_interval>               
  <preloader_on_reload>${settings.preloader_on_reload!}</preloader_on_reload>                 
  <add_time_stamp>${settings.add_time_stamp!}</add_time_stamp>                           
  <color_change_time_start>${settings.color_change_time_start!'0.5'}</color_change_time_start>      
  <color_change_time_hover>${settings.color_change_time_hover!}</color_change_time_hover>         
  <fit_to_screen>${settings.fit_to_screen!}</fit_to_screen>                             
  <drag_map>${settings.drag_map!'false'}</drag_map>                                       
  <always_hand>${settings.always_hand!'false'}</always_hand>                                 
  <mask>${settings.mask!}</mask>                                               
  <js_enabled>${settings.js_enabled!}</js_enabled>                                   
  <force_smoothing>${settings.force_smoothing!}</force_smoothing>                         
  <layers>${settings.layers!}</layers>																						 
  <background>                                                
    <color>${settings.background_color!'#FFFFFF'}</color>                                    
    <alpha>${settings.background_alpha!}</alpha>                                           
    <border_color>${settings.background_border_color!}</border_color>                             
    <border_alpha>${settings.background_border_alpha!}</border_alpha>                             
    <file>${settings.background_file!}</file>                                             
    <stretch>${settings.background_stretch!}</stretch>                                       
    <overlay_file>${settings.background_overlay_file!}</overlay_file>                             
    <overlay_stretch>${settings.background_overlay_stretch!}</overlay_stretch>                       
  </background>
  <zoom>                                                      
    <enabled>${settings.zoom_enabled!'false'}</enabled> 			   
    <locked>${settings.zoom_locked!}</locked>                                         
    <mouse_wheel_enabled>${settings.zoom_mouse_wheel_enabled!'false'}</mouse_wheel_enabled>	   	   
    <arrows_enabled>${settings.zoom_arrows_enabled!}</arrows_enabled>                         
    <home_link_enabled>${settings.zoom_home_link_enabled!}</home_link_enabled>                   
    <step_size>${settings.zoom_step_size!}</step_size>                                   
    <color>${settings.zoom_color!}</color>                         				   
    <color_hover>${settings.zoom_color_hover!}</color_hover>                               
    <alpha>${settings.zoom_alpha!}</alpha>                                           
    <outline_color>${settings.zoom_outline_color!}</outline_color>                           
    <outline_alpha>${settings.zoom_outline_alpha!}</outline_alpha>                           
    <x>${settings.zoom_x!}</x>                                                   
    <y>${settings.zoom_y!}</y>                                                   
    <height>${settings.zoom_height!}</height>                                         
    <min>${settings.zoom_min!}</min>                                               
    <max>${settings.zoom_max!}</max>                                               
    <grid_every>${settings.zoom_grid_every!}</grid_every>                                 
    <time>${settings.zoom_time!}</time>                                             
    <effect>${settings.zoom_effect!}</effect>                                         
    <rotate>${settings.zoom_rotate!}</rotate>                                         
    <background_zooms_to_top>${settings.zoom_background_zooms_to_top!'true'}</background_zooms_to_top>   
    <zoom_on_click>${settings.zoom_zoom_on_click!}</zoom_on_click>                           
  </zoom>
  <small_map>                                                 
    <enabled>${settings.small_map_enabled!'false'}</enabled>                                  
    <locked>${settings.small_map_locked!}</locked>                                         
    <active>${settings.small_map_active!}</active>                                         
    <x>${settings.small_map_x!}</x>                                                   
    <y>${settings.small_map_y!}</y>                                                   
    <width>${settings.small_map_width!}</width>                                           
    <color>${settings.small_map_color!}</color>                                           
    <border_width>${settings.small_map_border_width!}</border_width>                             
    <border_color>${settings.small_map_border_color!}</border_color>                             
    <rectangle_color>${settings.small_map_rectangle_color!}</rectangle_color>                       
    <collapse_button_color>${settings.small_map_collapse_button_color!}</collapse_button_color>           
    <collapse_button_position>${settings.small_map_collapse_button_position!}</collapse_button_position>     
  </small_map>
  <navigation_path>                                           
    <enabled>${settings.navigation_path_enabled!'false'}</enabled>                                  
    <x>${settings.navigation_path_x!}</x>                                                   
    <y>${settings.navigation_path_y!}</y>                                                   
    <color>${settings.navigation_path_color!}</color>                                           
    <alpha>${settings.navigation_path_alpha!}</alpha>                                           
    <padding>${settings.navigation_path_padding!}</padding>                                       
    <text_color>${settings.navigation_path_text_color!}</text_color>                                 
    <text_color_hover>${settings.navigation_path_text_color_hover!}</text_color_hover>                     
    <text_size>${settings.navigation_path_text_size!}</text_size>                                   
    <separator>${settings.navigation_path_separator!}</separator>                                   
    <home_text>${settings.navigation_path_home_text!}</home_text>                                   
  </navigation_path>
  <area>                                                      
    <balloon_text>${settings.area_balloon_text!'{title}'}</balloon_text>
    <active_only_if_value_set>${settings.area_active_only_if_value_set!}</active_only_if_value_set> 
    <color_solid>${settings.area_color_solid!'#CCFF00'}</color_solid>                               
    <color_light>${settings.area_color_light!'#CCFF00'}</color_light>                               
    <color_hover>${settings.area_color_hover!'#CC0000'}</color_hover>                        
    <color_selected>${settings.area_color_selected!}</color_selected>                          
    <color_unlisted>${settings.area_color_unlisted!}</color_unlisted>                         
    <disable_when_clicked>${settings.area_disable_when_clicked!'true'}</disable_when_clicked>         
  </area>
  <movie>                                                     
    <balloon_text>${settings.movie_balloon_text!'{title}'}</balloon_text>
    <active_only_if_value_set>${settings.movie_active_only_if_value_set!}</active_only_if_value_set>     
    <color>${settings.movie_color!}</color>                                           
    <color_hover>${settings.movie_color_hover!}</color_hover>                               
    <color_selected>${settings.movie_color_selected!}</color_selected>                         
  </movie>
  <label>                                                     
    <balloon_text>${settings.label_balloon_text!}</balloon_text>
    <bg_margins_horizontal>${settings.label_bg_margins_horizontal!}</bg_margins_horizontal>           
    <bg_margins_vertical>${settings.label_bg_margins_vertical!}</bg_margins_vertical>               
  </label>
  <line>                                                      
    <color>${settings.line_color!}</color>                                           
    <alpha>${settings.line_alpha!}</alpha>                                           
    <width>${settings.line_width!}</width>                                           
    <dashed>${settings.line_dashed!}</dashed>                                         
    <arrow>${settings.line_arrow!}</arrow>                                           
    <arrow_size>${settings.line_arrow_size!}</arrow_size>                                 
    <arrow_color>${settings.line_arrow_color!}</arrow_color>                               
    <arrow_alpha>${settings.line_arrow_alpha!}</arrow_alpha>                               
    <curved>${settings.line_curved!}</curved>                                         
  </line>
  <legend>                                                    
    <enabled>${settings.legend_enabled!}</enabled>                                       
    <x>${settings.legend_x!}</x>                                                   
    <y>${settings.legend_y!}</y>                                                   
    <width>${settings.legend_width!}</width>                                           
    <max_columns>${settings.legend_max_columns!}</max_columns>                                  
    <color>${settings.legend_color!}</color>                                           
    <alpha>${settings.legend_alpha!}</alpha>                                           
    <border_color>${settings.legend_border_color!}</border_color>                             
    <border_alpha>${settings.legend_border_alpha!}</border_alpha>                             
    <text_color>${settings.legend_text_color!}</text_color>                                   
    <text_size>${settings.legend_text_size!}</text_size>                                   
    <spacing>${settings.legend_spacing!}</spacing>                                       
    <margins>${settings.legend_margins!}</margins>                                       
    <key>${settings.legend_key!}</key>   
    <entries>${settings.legend_entries!}</entries>
  </legend>
  <object_list>                                               
    <enabled>${settings.object_list_enabled!}</enabled>                                       
    <type>${settings.object_list_type!}</type>                                             
    <levels>${settings.object_list_levels!}</levels>                                         
    <include_areas>${settings.object_list_include_areas!}</include_areas>                           
    <include_movies>${settings.object_list_include_movies!}</include_movies>                         
    <include_labels>${settings.object_list_include_labels!}</include_labels>                         
    <x>${settings.object_list_x!}</x>                                                   
    <y>${settings.object_list_y!}</y>                                                   
    <width>${settings.object_list_width!}</width>                                           
    <height>${settings.object_list_height!}</height>                                            
    <color>${settings.object_list_color!}</color>                                           
    <color_hover>${settings.object_list_color_hover!}</color_hover>                               
    <color_selected>${settings.object_list_color_selected!}</color_selected>                         
    <alpha>${settings.object_list_alpha!}</alpha>                                           
    <border_color>${settings.object_list_border_color!}</border_color>                             
    <border_alpha>${settings.object_list_border_alpha!}</border_alpha>                             
    <text_color>${settings.object_list_text_color!}</text_color>                                 
    <text_color_hover>${settings.object_list_text_color_hover!}</text_color_hover>                     
    <text_color_selected>${settings.object_list_text_color_selected!}</text_color_selected>                 
    <text_size>${settings.object_list_text_size!}</text_size>                                   
    <scroller_color>${settings.object_list_scroller_color!}</scroller_color>                         
    <scroller_bg_color>${settings.object_list_scroller_bg_color!}</scroller_bg_color>                   
    <home_text>${settings.object_list_home_text!}</home_text>                                   
  </object_list> 
  <text_box>                                                  
    <enabled>${settings.text_box_enabled!}</enabled>                                       
    <locked>${settings.text_box_locked!}</locked>                                         
    <selectable>${settings.text_box_selectable!}</selectable>                                 
    <show_on_hover>${settings.text_box_show_on_hover!}</show_on_hover>                           
    <hide_on_roll_out>${settings.text_box_hide_on_roll_out!}</hide_on_roll_out>                     
    <x>${settings.text_box_x!}</x>                                                   
    <y>${settings.text_box_y!}</y>                                                   
    <width>${settings.text_box_width!}</width>                                           
    <height>${settings.text_box_height!}</height>                                         
    <color>${settings.text_box_color!}</color>                                           
    <alpha>${settings.text_box_alpha!}</alpha>                                           
    <shadow_color>${settings.text_box_shadow_color!}</shadow_color>                             
    <shadow_alpha>${settings.text_box_shadow_alpha!}</shadow_alpha>                             
    <shadow_blur>${settings.text_box_shadow_blur!}</shadow_blur>                               
    <shadow_distance>${settings.text_box_shadow_distance!}</shadow_distance>                       
    <corner_radius>${settings.text_box_corner_radius!'7'}</corner_radius>                           
    <border_width>${settings.text_box_border_width!}</border_width>                             
    <border_color>${settings.text_box_border_color!}</border_color>                             
    <border_alpha>${settings.text_box_border_alpha!}</border_alpha>                             
    <margin_width>${settings.text_box_margin_width!}</margin_width>                             
    <text_size>${settings.text_box_text_size!}</text_size>                                   
    <text_color>${settings.text_box_text_color!}</text_color>                                 
    <close_button_color>${settings.text_box_close_button_color!}</close_button_color>                 
    <close_button_color_hover>${settings.text_box_close_button_color_hover!}</close_button_color_hover>     
    <scroller_color>${settings.text_box_scroller_color!}</scroller_color>                         
    <scroller_bg_color>${settings.text_box_scroller_bg_color!}</scroller_bg_color>                   
  </text_box>
  <balloon>                                                   
    <enabled>${settings.balloon_enabled!}</enabled>                                       
    <max_width>${settings.balloon_max_width!}</max_width>                                   
    <color>${settings.balloon_color!}</color>                                           
    <alpha>${settings.balloon_alpha!}</alpha>                                           
    <text_color>${settings.balloon_text_color!}</text_color>                                 
    <text_size>${settings.balloon_text_size!}</text_size>                                   
    <border_color>${settings.balloon_border_color!}</border_color>                             
    <border_alpha>${settings.balloon_border_alpha!}</border_alpha>                             
    <border_width>${settings.balloon_border_width!}</border_width>                             
    <corner_radius>${settings.balloon_corner_radius!}</corner_radius>                           
    <arrow>${settings.balloon_arrow!}</arrow>                                           
  </balloon>
  <export_as_image>                                           
    <file>${settings.export_as_image_file!}</file>                                             
    <target>${settings.export_as_image_target!}</target>                                         
    <x>${settings.export_as_image_x!}</x>                                                   
    <y>${settings.export_as_image_y!}</y>                                                   
    <color>${settings.export_as_image_color!}</color>                                           
    <alpha>${settings.export_as_image_alpha!}</alpha>                                           
    <text_color>${settings.export_as_image_text_color!}</text_color>                                 
    <text_size>${settings.export_as_image_text_size!}</text_size>                                   
  </export_as_image>
  <strings>
    <loading_map>${settings.strings_loading_map!}</loading_map>                               
    <export_as_image>${settings.strings_export_as_image!}</export_as_image>                       
    <collecting_data>${settings.strings_collecting_data!}</collecting_data>                       
  </strings>
</settings>